#Hugo configuration
title = "3rfdggdf"
baseURL = "https:\/\/23rrdf.asd.er"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
